import type { MetadataRoute } from 'next';

/**
 * PWA manifest. `pericles-mobile` makes the PWA over `frontend/` the preferred
 * V1 mobile client, so this is the install surface on iOS and Android.
 *
 * Next serves this at /manifest.webmanifest and injects the <link> itself — do
 * not also set `manifest` in the root layout's metadata.
 *
 * `icons` points at public/icon-{192,512}.png, generated by
 * `scripts/generate-pwa-icons.mjs` — a placeholder gold "P" monogram, since
 * no brand logomark exists yet (the sidebar wordmark is styled text, not a
 * graphic mark). Both sizes are required for the install prompt on iOS and
 * Android (#30). Replace the PNGs with real brand art when it exists; the
 * generator script documents how to regenerate or retire itself.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Pericles — Supply Chain Risk Management',
    short_name: 'Pericles',
    description:
      'AI-powered supply chain risk monitoring and incident management',
    start_url: '/',
    display: 'standalone',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    // No `orientation` lock: WCAG 1.3.4 prohibits restricting to a single
    // orientation unless essential, and Atlas is a full-screen map that is
    // materially better in landscape.
    // A manifest can only encode ONE value, but the shell now flips with the
    // mode (--sidebar is purple-100 light / purple-600 dark) and layout.tsx
    // declares both. purple-600 is the deliberate choice for the install
    // splash and standalone chrome; an installed light-mode user therefore
    // gets purple-600 chrome above a purple-100 header. Fixing that properly
    // needs a runtime theme-color update, not a manifest change.
    background_color: '#524765',
    theme_color: '#524765',
  };
}
